version: '3.8'

services:
  musicbro:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: musicbro
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=your_discord_token_here
    volumes:
      - /mnt/docker/musicbro/autoplaylists:/app/autoplaylists
      - /mnt/docker/musicbro/downloads:/app/downloads